[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ch-tools"
version = "1.0.0"
description = "A set of tools for administration and diagnostics of ClickHouse DBMS."
readme = "README.md"
requires-python = ">=3.6"
license = { file="LICENSE" }
authors = [
    { name="Alexander Burmak", email="alex-burmak@yandex-team.ru"},
    { name="Dmitry Starov", email="dstaroff@yandex-team.ru"},
    { name="Anton Ivashkin", email="iantonspb@yandex-team.ru"},
    { name="Grigory Pervakov", email="pervakovg@yandex-team.ru"},
    { name="Petr Nuzhnov", email="petrnuzhnov@yandex-team.ru"},
    { name="Egor Medvedev", email="egor-medvedev@yandex-team.ru"},
    { name="Aleksei Filatov", email="alexfvk@yandex-team.ru"},
    { name="Evgeny Dyukov", email="secwall@yandex-team.ru"},
    { name="Evgeny Strizhnev", email="estrizhnev@yandex-team.ru"},
    { name="Vadim Volodin", email="vadim-volodin@yandex-team.ru"},
    { name="Anton Chaporgin", email="chapson@yandex-team.ru"},
    { name="Evgenii Kopanev", email="ekopanev@yandex-team.ru"},
    { name="Mikhail Kot", email="myrrc@yandex-team.ru"},
]
maintainers = [
    { name="Alexander Burmak", email="alex-burmak@yandex-team.ru"},
    { name="Dmitry Starov", email="dstaroff@yandex-team.ru"},
    { name="Anton Ivashkin", email="iantonspb@yandex-team.ru"},
    { name="Grigory Pervakov", email="pervakovg@yandex-team.ru"},
    { name="Petr Nuzhnov", email="petrnuzhnov@yandex-team.ru"},
    { name="Egor Medvedev", email="egor-medvedev@yandex-team.ru"},
    { name="Aleksei Filatov", email="alexfvk@yandex-team.ru"},
    { name="Evgenii Kopanev", email="ekopanev@yandex-team.ru"},
    { name="Mikhail Kot", email="myrrc@yandex-team.ru"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: BSD",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Database",
    "Typing :: Typed",
]
dependencies = [
    "Jinja2 >= 3.0.0",
    "PyYAML >= 5.4.0",
    "Pygments >= 2.14.0",
    "boto3 >= 1.23.0",
    "click >= 8.0.0",
    "cloup >= 0.15.0",
    "deepdiff >= 5.7.0",
    "dnspython >= 2.2.0",
    "humanfriendly >= 10.0",
    "kazoo >= 2.9",
    "lxml >= 4.9.0",
    "psutil >= 5.9.0",
    "pyOpenSSL >= 23.2.0",
    "python-dateutil >= 2.8.0",
    "requests >= 2.27.0",
    "setuptools >= 59.6.0",
    "tabulate >= 0.8.0",
    "tenacity >= 8.2.0",
    "termcolor >= 1.1.0",
    "tqdm >= 4.64.0",
    "xmltodict >= 0.13.0",
]

[project.optional-dependencies]
dev = [
    "behave >= 1.2.0",
    "black >= 22.8.0",
    "docker >= 5.0.0",
    "docker-compose >= 1.29.0",
    "flake8 >= 5.0.0",
    "flake8-commas >= 2.1.0",
    "flake8-print >= 4.0.0",
    "flake8-quotes >= 3.3.0",
    "flake8-string-format >= 0.3.0",
    "isort >= 5.10.0",
    "mypy >= 0.971",
    "pep8 >= 1.7.0",
    "PyHamcrest >= 2.0.0",
    "pylint >= 2.13.0",
    "pytest >= 7.0.0",
]

[project.urls]
"Source" = "https://github.com/yandex/ch-tools"

[project.scripts]
chadmin = "chtools.chadmin.chadmin_cli:main"
ch-monitoring = "chtools.monrun_checks.main:main"
keeper-monitoring = "chtools.monrun_checks_keeper.main:main"
ch-s3-credentials = "chtools.s3_credentials.main:main"
